apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: [ 'sh', '-c', 'until nc -z db 5432; do echo waiting for db; sleep 2; done;' ]
      containers:
        - name: app
          image: {{ .Values.image.repository }}/calendar-app:{{ .Values.image.tag }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-app-env
            - secretRef:
                name: {{ .Release.Name }}-app-secret
          ports:
            - containerPort: {{ .Values.service.port }}