apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-env
data:
  HTTP_PORT: "{{ .Values.app.env.HTTP_PORT }}"
  GRPC_PORT: "{{ .Values.app.env.GRPC_PORT }}"
  POSTGRES_HOST: "{{ .Values.app.env.POSTGRES_HOST }}"
  POSTGRES_DB: "{{ .Values.app.env.POSTGRES_DB }}"
  POSTGRES_PORT: "{{ .Values.app.env.POSTGRES_PORT }}"
  POSTGRES_USER: "{{ .Values.app.env.POSTGRES_USER }}"
  RMQ_USER: "{{ .Values.app.env.RMQ_USER }}"
  RMQ_PORT: "{{ .Values.app.env.RMQ_PORT }}"
  RMQ_DISK_FREE: "{{ .Values.app.env.RMQ_DISK_FREE }}"