// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/client/db/transaction/transaction.go
//
// Generated by this command:
//
//	mockgen -source=../internal/client/db/transaction/transaction.go -destination=db/tx_manager_mock.go -package=dbmocks
//

// Package dbmocks is a generated GoMock package.
package dbmocks
