run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax
        files:
          - "!**/*_a _file.go"
          - "!$test"
        allow:
          - $gostd
          - github.com/jackc/pgconn
          - github.com/Tel3scop/otus_go
          - github.com/Masterminds/squirrel
          - github.com/Tel3scop/helpers
          - github.com/jackc/pgx
          - github.com/georgysavva/scany
          - github.com/pkg/errors
          - github.com/grpc-ecosystem
          - github.com/spf13/cobra
          - github.com/google/uuid
          - github.com/rs/cors
          - github.com/rakyll/statik/fs

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - revive
        - unparam
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
