// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/storage/event.go
//
// Generated by this command:
//
//	mockgen -source=../internal/storage/event.go -destination=storage/event.go -package=eventRepositoryMocks
//

// Package eventRepositoryMocks is a generated GoMock package.
package eventRepositoryMocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/Tel3scop/otus_go/hw12_13_14_15_calendar/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockEventStorage is a mock of EventStorage interface.
type MockEventStorage struct {
	ctrl     *gomock.Controller
	recorder *MockEventStorageMockRecorder
}

// MockEventStorageMockRecorder is the mock recorder for MockEventStorage.
type MockEventStorageMockRecorder struct {
	mock *MockEventStorage
}

// NewMockEventStorage creates a new mock instance.
func NewMockEventStorage(ctrl *gomock.Controller) *MockEventStorage {
	mock := &MockEventStorage{ctrl: ctrl}
	mock.recorder = &MockEventStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStorage) EXPECT() *MockEventStorageMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEventStorage) Create(ctx context.Context, event entity.Event) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEventStorageMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventStorage)(nil).Create), ctx, event)
}

// Delete mocks base method.
func (m *MockEventStorage) Delete(ctx context.Context, eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEventStorageMockRecorder) Delete(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventStorage)(nil).Delete), ctx, eventID)
}

// List mocks base method.
func (m *MockEventStorage) List(ctx context.Context, date time.Time, period entity.PeriodType) ([]entity.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, date, period)
	ret0, _ := ret[0].([]entity.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEventStorageMockRecorder) List(ctx, date, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEventStorage)(nil).List), ctx, date, period)
}

// Update mocks base method.
func (m *MockEventStorage) Update(ctx context.Context, eventID string, event entity.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, eventID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEventStorageMockRecorder) Update(ctx, eventID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEventStorage)(nil).Update), ctx, eventID, event)
}
